### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shash-sixwheel** [JulianSchmid/example-bazel-add-git-hash#1]
Hello,

I found the example to be quite helpful, and I would like to use this as a reference. Specifically the part where the .h file is generated via a python script, and the usage of --workspace_status_command.

However, since this project is unlicensed, that means that the author currently reserves all rights; thus I am forbidden from borrowing or modifying any of this.

Would you mind adding a permissive license to this project?

Thank you very much :)

Shashwat

**Comment by JulianSchmid** [comment]
Hi,

I added the Apache 2.0 license as license.

Enjoy & Greets
Julian

**Comment by shash-sixwheel** [comment]
Appreciate the fast response!! Thanks again :D

**Comment by JulianSchmid** [comment]
And I switched to the MIT license (just so I don't have to add file comments everywhere).
